### ISSUE TITLE
Print result does not work

### ISSUE THREAD

**Issue by Dellos7** [deckgo/deckdeckgo-starter#28]
Hello @peterpeterparker,

I was just trying the print result button but it seems not to be working, at least from my computer, as shown in this screenshot:

![deckdeckgo print](https://i.imgur.com/mZOz6z9.jpg)

Result is just a blank page. Could you please confirm this?

I've tried it in Chrome and Safari.

Thank you.

David.

**Comment by peterpeterparker** [comment]
@Dellos7 the related commit of this issue solves it partially, as it will only be possible to print using the "print" button in the fab-button (bottom right of the presentation) as a not exposed  style of `ion-content` has to be modified in the shadowed element

also note, the pagination will be improved with the next version of DeckDeckGo (added a page break after each slides) but I'm currently unable to release as I'm facing the following Stencil issue: https://github.com/ionic-team/stencil/issues/1308

Anyhow I close this issue as it's solve from my side...keep me posted and thx a lot for the feedback 👍

**Comment by Dellos7** [comment]
Hello @peterpeterparker, thank you very much!

Just to know, how do you update your own dekdeckgo projects so to use the last release of the starter kit? I mean I was thinking in you know `git pull` from the remote branch of the starter kit repo, but you might change the `index.html` and conflicts may appear. Do you use any other technique?

Thank you again, you are super fast!!

**Comment by peterpeterparker** [comment]
@Dellos7 right now there isn't a super easy straight forward way to do it. 

What I do for the deckdeckgo-website is I always install the last libs to reflect the version of the starter kit and then I make manually the js scripts or html changes I would have done in the starter kit (I reflect manually the changes)

At some point I'll probably have to create kind of a library for the js scripts, css and dependencies of the starter kit, that would make things easier

Do that help?

**Comment by peterpeterparker** [comment]
@Dellos7 FYI the new version has just been released. this version contains the improvement I mentioned about printing and pagination :)

https://github.com/deckgo/deckdeckgo-starter/blob/master/CHANGELOG.md
